"""
apps_data.py
------------
The research output for all 100 apps, as a structured Python list.

This is the artifact the research agent (research_agent.py) produces: for each
app it extracts a fixed schema of fields, an evidence URL, and a self-reported
confidence. Low-confidence rows are the ones the agent flagged for a human.

Schema per app:
  id            int
  name          str
  website       str        # docs / hint URL from the brief
  category      str        # one of 10 categories
  one_liner     str        # what it does, one line
  auth          str        # primary auth method(s)
  self_serve    str        # "self-serve" | "gated" | "partial"
  serve_note    str        # how you actually get credentials
  api_surface   str        # REST / GraphQL, rough breadth
  mcp           str        # "yes" | "community" | "no" | "unknown"
  verdict       str        # "easy" | "buildable" | "gated" | "needs-human"
  blocker       str        # main blocker to building a toolkit today ("" if none)
  evidence      str        # docs URL behind the answer
  confidence    str        # "high" | "medium" | "low"  (agent's self-report)
"""

APPS = [
    # ------------------------------------------------------------------ #
    # 1. CRM and Sales
    # ------------------------------------------------------------------ #
    dict(id=1, name="Salesforce", website="salesforce.com", category="CRM & Sales",
         one_liner="Enterprise CRM and application platform.",
         auth="OAuth2 (also JWT bearer, username-password flow)",
         self_serve="self-serve", serve_note="Free Developer Edition org gives full API access; must create a Connected App.",
         api_surface="Very broad: REST, SOAP, Bulk, Streaming, plus a GraphQL API.",
         mcp="community", verdict="buildable",
         blocker="Connected App + OAuth setup is heavy; many API variants to cover.",
         evidence="https://developer.salesforce.com/docs/apis", confidence="high"),
    dict(id=2, name="HubSpot", website="hubspot.com", category="CRM & Sales",
         one_liner="CRM plus marketing, sales and service hubs.",
         auth="OAuth2 + Private App access tokens (legacy API keys deprecated)",
         self_serve="self-serve", serve_note="Free developer account; create a private app to get a token instantly.",
         api_surface="Broad REST API v3 across CRM objects, marketing, automation.",
         mcp="community", verdict="easy", blocker="",
         evidence="https://developers.hubspot.com/docs/api/overview", confidence="high"),
    dict(id=3, name="Pipedrive", website="pipedrive.com", category="CRM & Sales",
         one_liner="Sales-focused CRM and pipeline tool.",
         auth="API token + OAuth2",
         self_serve="self-serve", serve_note="Trial account; personal API token available in settings.",
         api_surface="REST API v1/v2, well documented.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developers.pipedrive.com/docs/api/v1", confidence="high"),
    dict(id=4, name="Attio", website="attio.com", category="CRM & Sales",
         one_liner="Modern, data-model-flexible CRM.",
         auth="OAuth2 + API key (Bearer)",
         self_serve="self-serve", serve_note="Free workspace; generate API key in settings.",
         api_surface="REST API covering records, lists, objects.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developers.attio.com/", confidence="high"),
    dict(id=5, name="Twenty", website="twenty.com", category="CRM & Sales",
         one_liner="Open-source CRM.",
         auth="API key (Bearer) + GraphQL",
         self_serve="self-serve", serve_note="Self-host free or use cloud; token from settings.",
         api_surface="GraphQL API (plus REST); schema is generated from your data model.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://twenty.com/developers", confidence="high"),
    dict(id=6, name="Podio", website="podio.com", category="CRM & Sales",
         one_liner="Flexible work/collaboration + CRM platform.",
         auth="OAuth2",
         self_serve="self-serve", serve_note="Free tier limited; register an API client.",
         api_surface="REST API; mature but aging platform.",
         mcp="no", verdict="buildable",
         blocker="Aging platform, uneven docs.",
         evidence="https://developers.podio.com/", confidence="medium"),
    dict(id=7, name="Zoho CRM", website="zoho.com/crm", category="CRM & Sales",
         one_liner="CRM within the broad Zoho suite.",
         auth="OAuth2 (self-client)",
         self_serve="self-serve", serve_note="Free tier + developer console; self-client for tokens.",
         api_surface="Broad REST API; region-specific data centers.",
         mcp="no", verdict="buildable",
         blocker="OAuth self-client + multi-DC region handling.",
         evidence="https://www.zoho.com/crm/developer/docs/api/v6/", confidence="high"),
    dict(id=8, name="Close", website="close.com", category="CRM & Sales",
         one_liner="Inside-sales CRM with built-in calling.",
         auth="API key (HTTP Basic with key as username)",
         self_serve="self-serve", serve_note="Trial; API key in settings.",
         api_surface="REST API, well documented.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.close.com/", confidence="high"),
    dict(id=9, name="Copper", website="copper.com", category="CRM & Sales",
         one_liner="CRM built for Google Workspace.",
         auth="API key (token + email headers)",
         self_serve="self-serve", serve_note="API key generated in settings.",
         api_surface="REST API (developer API).",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.copper.com/", confidence="high"),
    dict(id=10, name="DealCloud", website="api.docs.dealcloud.com", category="CRM & Sales",
         one_liner="CRM/deal platform for PE and capital markets (Intapp).",
         auth="OAuth2 / token",
         self_serve="gated", serve_note="Enterprise product; credentials require an account and admin setup, effectively contact-sales.",
         api_surface="Documented REST API.",
         mcp="no", verdict="gated",
         blocker="Enterprise gate: no self-serve credentials, needs partnership/customer account.",
         evidence="https://api.docs.dealcloud.com/", confidence="medium"),

    # ------------------------------------------------------------------ #
    # 2. Support and Helpdesk
    # ------------------------------------------------------------------ #
    dict(id=11, name="Zendesk", website="zendesk.com", category="Support & Helpdesk",
         one_liner="Customer support ticketing suite.",
         auth="OAuth2 + API token + Basic",
         self_serve="self-serve", serve_note="Trial account; API token in admin center.",
         api_surface="Very broad REST API (tickets, users, help center, etc.).",
         mcp="community", verdict="easy", blocker="",
         evidence="https://developer.zendesk.com/api-reference/", confidence="high"),
    dict(id=12, name="Intercom", website="intercom.com", category="Support & Helpdesk",
         one_liner="Customer messaging and support platform.",
         auth="OAuth2 + access token",
         self_serve="self-serve", serve_note="Developer workspace; access token from developer hub.",
         api_surface="Broad REST API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://developers.intercom.com/docs/references/rest-api/", confidence="high"),
    dict(id=13, name="Freshdesk", website="freshdesk.com", category="Support & Helpdesk",
         one_liner="Support ticketing (Freshworks).",
         auth="API key (HTTP Basic)",
         self_serve="self-serve", serve_note="Trial; API key in profile settings.",
         api_surface="REST API v2.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developers.freshdesk.com/api/", confidence="high"),
    dict(id=14, name="Front", website="front.com", category="Support & Helpdesk",
         one_liner="Shared inbox / customer ops platform.",
         auth="API token (JWT) + OAuth2",
         self_serve="self-serve", serve_note="API token from settings.",
         api_surface="REST API (Core API).",
         mcp="no", verdict="easy", blocker="",
         evidence="https://dev.frontapp.com/", confidence="high"),
    dict(id=15, name="Pylon", website="usepylon.com", category="Support & Helpdesk",
         one_liner="B2B support platform (Slack-native).",
         auth="API key (Bearer)",
         self_serve="self-serve", serve_note="Admin users generate an API token in the dashboard.",
         api_surface="Broad REST API (issues, accounts, contacts, KB, messages, teams, webhooks).",
         mcp="yes", verdict="easy",
         blocker="",
         evidence="https://docs.usepylon.com/pylon-docs/developer/api/authentication", confidence="high",
         verified=True, first_pass=dict(mcp="no", verdict="buildable", api_surface="REST API, growing.", confidence="low")),
    dict(id=16, name="LiveAgent", website="liveagent.com", category="Support & Helpdesk",
         one_liner="Helpdesk with live chat and call center.",
         auth="API key",
         self_serve="self-serve", serve_note="API key in settings.",
         api_surface="REST API v3.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://docs.liveagent.com/", confidence="medium"),
    dict(id=17, name="Plain", website="plain.com", category="Support & Helpdesk",
         one_liner="Developer-first B2B support platform.",
         auth="API key + GraphQL",
         self_serve="self-serve", serve_note="API key from settings.",
         api_surface="GraphQL-native API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://www.plain.com/docs/api-reference/graphql", confidence="high"),
    dict(id=18, name="Help Scout", website="helpscout.com", category="Support & Helpdesk",
         one_liner="Email-based customer support.",
         auth="OAuth2 + API key",
         self_serve="self-serve", serve_note="Create an app for OAuth or use API key.",
         api_surface="REST API (Mailbox API v2).",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.helpscout.com/mailbox-api/", confidence="high"),
    dict(id=19, name="Gorgias", website="gorgias.com", category="Support & Helpdesk",
         one_liner="Ecommerce-focused helpdesk.",
         auth="Basic (API key) + OAuth2",
         self_serve="self-serve", serve_note="API key in settings.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developers.gorgias.com/", confidence="high"),
    dict(id=20, name="Gladly", website="gladly.com", category="Support & Helpdesk",
         one_liner="People-centered customer service platform.",
         auth="API token (HTTP Basic with token)",
         self_serve="partial", serve_note="Docs are public but you need a Gladly account (sales-led) to get credentials.",
         api_surface="Documented REST API.",
         mcp="no", verdict="buildable",
         blocker="Account is sales-led; no free self-serve credential path.",
         evidence="https://developer.gladly.com/", confidence="medium"),

    # ------------------------------------------------------------------ #
    # 3. Communications and Messaging
    # ------------------------------------------------------------------ #
    dict(id=21, name="Slack", website="slack.com", category="Communications & Messaging",
         one_liner="Team messaging platform.",
         auth="OAuth2 (bot & user tokens)",
         self_serve="self-serve", serve_note="Free workspace; create an app in the developer portal.",
         api_surface="Very broad Web API + Events + Socket Mode.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://api.slack.com/", confidence="high"),
    dict(id=22, name="Twilio", website="twilio.com", category="Communications & Messaging",
         one_liner="Programmable SMS, voice and messaging.",
         auth="Basic (Account SID + Auth Token) / API keys",
         self_serve="self-serve", serve_note="Free trial with credit; keys in console.",
         api_surface="Broad REST API across many products.",
         mcp="community", verdict="easy", blocker="",
         evidence="https://www.twilio.com/docs/usage/api", confidence="high"),
    dict(id=23, name="Zoho Cliq", website="zoho.com/cliq", category="Communications & Messaging",
         one_liner="Team messaging in the Zoho suite.",
         auth="OAuth2",
         self_serve="self-serve", serve_note="Zoho developer console; OAuth self-client.",
         api_surface="REST API.",
         mcp="no", verdict="buildable",
         blocker="Zoho OAuth + region data centers.",
         evidence="https://www.zoho.com/cliq/help/restapi/", confidence="medium"),
    dict(id=24, name="Lark (Larksuite)", website="open.larksuite.com", category="Communications & Messaging",
         one_liner="All-in-one collaboration suite (intl. Feishu).",
         auth="OAuth2 (tenant/app access tokens)",
         self_serve="self-serve", serve_note="Developer console; create a custom app.",
         api_surface="Broad Open API (messaging, docs, calendar, etc.).",
         mcp="no", verdict="buildable",
         blocker="Tenant vs user token model adds complexity.",
         evidence="https://open.larksuite.com/document", confidence="medium"),
    dict(id=25, name="Pumble", website="pumble.com", category="Communications & Messaging",
         one_liner="Team chat app (CAKE.com).",
         auth="API key",
         self_serve="partial", serve_note="API exists but is thin; key from settings.",
         api_surface="Limited REST API.",
         mcp="no", verdict="buildable",
         blocker="API is narrow relative to competitors.",
         evidence="https://pumble.com/help/integrations/add-pumble-api/", confidence="low"),
    dict(id=26, name="Discord", website="discord.com", category="Communications & Messaging",
         one_liner="Community chat and voice platform.",
         auth="OAuth2 + Bot token",
         self_serve="self-serve", serve_note="Free developer portal; create an application/bot.",
         api_surface="Broad REST API + Gateway (WebSocket).",
         mcp="community", verdict="easy", blocker="",
         evidence="https://discord.com/developers/docs/intro", confidence="high"),
    dict(id=27, name="Telegram", website="core.telegram.org", category="Communications & Messaging",
         one_liner="Messaging platform with an open bot API.",
         auth="Bot token",
         self_serve="self-serve", serve_note="Create a bot via @BotFather, instant token.",
         api_surface="Bot API (REST) + MTProto (client API).",
         mcp="community", verdict="easy", blocker="",
         evidence="https://core.telegram.org/bots/api", confidence="high"),
    dict(id=28, name="WhatsApp Business", website="developers.facebook.com/docs/whatsapp", category="Communications & Messaging",
         one_liner="Business messaging over WhatsApp (Meta).",
         auth="OAuth2 (Meta) / system-user tokens",
         self_serve="partial", serve_note="Meta developer account is free, but production needs business verification + approved WABA.",
         api_surface="Graph API (Cloud API).",
         mcp="no", verdict="buildable",
         blocker="Business verification and number onboarding gate production use.",
         evidence="https://developers.facebook.com/docs/whatsapp", confidence="high"),
    dict(id=29, name="Aircall", website="aircall.io", category="Communications & Messaging",
         one_liner="Cloud phone/call center.",
         auth="API key (Basic: API ID + token)",
         self_serve="self-serve", serve_note="API credentials in dashboard.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.aircall.io/", confidence="high"),
    dict(id=30, name="Vonage", website="developer.vonage.com", category="Communications & Messaging",
         one_liner="Communications APIs (SMS, voice, verify).",
         auth="API key+secret / JWT (app-based)",
         self_serve="self-serve", serve_note="Free trial with credit; keys in dashboard.",
         api_surface="REST API across products.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.vonage.com/en/documentation", confidence="high"),

    # ------------------------------------------------------------------ #
    # 4. Marketing, Ads, Email and Social
    # ------------------------------------------------------------------ #
    dict(id=31, name="Google Ads", website="developers.google.com/google-ads", category="Marketing, Ads, Email & Social",
         one_liner="Google's advertising platform.",
         auth="OAuth2 + developer token",
         self_serve="gated", serve_note="OAuth is self-serve, but a developer token must be approved by Google before production access.",
         api_surface="Broad API using GAQL query language.",
         mcp="no", verdict="buildable",
         blocker="Developer-token approval; standard access requires review.",
         evidence="https://developers.google.com/google-ads/api/docs/start", confidence="high"),
    dict(id=32, name="Meta Ads", website="developers.facebook.com/docs/marketing-apis", category="Marketing, Ads, Email & Social",
         one_liner="Advertising across Facebook/Instagram.",
         auth="OAuth2 (Meta)",
         self_serve="gated", serve_note="App review + business verification required for ads permissions.",
         api_surface="Graph Marketing API, broad.",
         mcp="no", verdict="buildable",
         blocker="App review + advanced-access approval for ads scopes.",
         evidence="https://developers.facebook.com/docs/marketing-apis", confidence="high"),
    dict(id=33, name="LinkedIn Ads", website="learn.microsoft.com/linkedin/marketing", category="Marketing, Ads, Email & Social",
         one_liner="LinkedIn advertising / marketing.",
         auth="OAuth2",
         self_serve="gated", serve_note="Marketing Developer Platform access requires application/partner approval.",
         api_surface="Marketing API.",
         mcp="no", verdict="gated",
         blocker="Partner program approval is required before real access.",
         evidence="https://learn.microsoft.com/en-us/linkedin/marketing/", confidence="high"),
    dict(id=34, name="GoHighLevel", website="highlevel.stoplight.io", category="Marketing, Ads, Email & Social",
         one_liner="Agency marketing/CRM all-in-one.",
         auth="OAuth2 + API key",
         self_serve="partial", serve_note="Needs an (paid) account; then OAuth/API access is self-serve.",
         api_surface="REST API v2.",
         mcp="no", verdict="buildable",
         blocker="Requires a paid agency account to obtain credentials.",
         evidence="https://highlevel.stoplight.io/", confidence="medium"),
    dict(id=35, name="Mailchimp", website="mailchimp.com/developer", category="Marketing, Ads, Email & Social",
         one_liner="Email marketing automation.",
         auth="OAuth2 + API key",
         self_serve="self-serve", serve_note="Free account; API key in settings.",
         api_surface="REST API (Marketing API).",
         mcp="no", verdict="easy", blocker="",
         evidence="https://mailchimp.com/developer/marketing/api/", confidence="high"),
    dict(id=36, name="Klaviyo", website="developers.klaviyo.com", category="Marketing, Ads, Email & Social",
         one_liner="Ecommerce email/SMS marketing.",
         auth="API key (private) + OAuth2",
         self_serve="self-serve", serve_note="Free account; private API key in settings.",
         api_surface="REST API, versioned by date.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developers.klaviyo.com/en", confidence="high"),
    dict(id=37, name="systeme.io", website="systeme.io", category="Marketing, Ads, Email & Social",
         one_liner="All-in-one funnel/marketing builder.",
         auth="API key",
         self_serve="self-serve", serve_note="API key in account settings.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.systeme.io/", confidence="medium"),
    dict(id=38, name="Pinterest", website="developers.pinterest.com", category="Marketing, Ads, Email & Social",
         one_liner="Visual discovery / social platform.",
         auth="OAuth2",
         self_serve="partial", serve_note="Developer app is self-serve; some scopes need app review for standard access.",
         api_surface="REST API v5.",
         mcp="no", verdict="buildable",
         blocker="App review for elevated access.",
         evidence="https://developers.pinterest.com/docs/api/v5/", confidence="high"),
    dict(id=39, name="Threads (Meta)", website="developers.facebook.com/docs/threads", category="Marketing, Ads, Email & Social",
         one_liner="Meta's text-based social app.",
         auth="OAuth2 (Meta)",
         self_serve="partial", serve_note="Threads API is generally available; Meta app + permissions apply.",
         api_surface="Graph API (Threads), newer/limited.",
         mcp="no", verdict="buildable",
         blocker="Newer API; scope/permission review.",
         evidence="https://developers.facebook.com/docs/threads", confidence="medium"),
    dict(id=40, name="SendGrid", website="sendgrid.com", category="Marketing, Ads, Email & Social",
         one_liner="Transactional and marketing email (Twilio).",
         auth="API key (Bearer)",
         self_serve="self-serve", serve_note="Free tier; API key in settings.",
         api_surface="REST API v3.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://www.twilio.com/docs/sendgrid/api-reference", confidence="high"),

    # ------------------------------------------------------------------ #
    # 5. Ecommerce
    # ------------------------------------------------------------------ #
    dict(id=41, name="Shopify", website="shopify.dev", category="Ecommerce",
         one_liner="Leading commerce platform.",
         auth="OAuth2 (apps) + Admin API access token",
         self_serve="self-serve", serve_note="Free development store; create an app for tokens.",
         api_surface="Very broad: GraphQL Admin API (primary) + REST + Storefront.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://shopify.dev/docs/api", confidence="high"),
    dict(id=42, name="WooCommerce", website="woocommerce.com/document/woocommerce-rest-api", category="Ecommerce",
         one_liner="WordPress ecommerce plugin.",
         auth="API key (consumer key/secret, Basic)",
         self_serve="self-serve", serve_note="Self-hosted WordPress; generate keys in WooCommerce settings.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://woocommerce.github.io/woocommerce-rest-api-docs/", confidence="high"),
    dict(id=43, name="BigCommerce", website="developer.bigcommerce.com", category="Ecommerce",
         one_liner="Headless-friendly ecommerce platform.",
         auth="OAuth2 + API token (X-Auth-Token)",
         self_serve="self-serve", serve_note="Trial store; API account gives token.",
         api_surface="REST + GraphQL (Storefront).",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.bigcommerce.com/docs", confidence="high"),
    dict(id=44, name="Salesforce Commerce Cloud", website="developer.salesforce.com/docs/commerce", category="Ecommerce",
         one_liner="Enterprise B2C/B2B commerce (Demandware).",
         auth="OAuth2 (SLAS)",
         self_serve="gated", serve_note="Requires a B2C Commerce instance; enterprise, sales-led.",
         api_surface="SCAPI / OCAPI.",
         mcp="no", verdict="gated",
         blocker="Enterprise instance required; no self-serve sandbox for outsiders.",
         evidence="https://developer.salesforce.com/docs/commerce/commerce-api", confidence="medium"),
    dict(id=45, name="Magento (Adobe Commerce)", website="developer.adobe.com/commerce", category="Ecommerce",
         one_liner="Open-source + enterprise commerce.",
         auth="OAuth 1.0a / token / Bearer",
         self_serve="self-serve", serve_note="Open-source edition self-hostable; create integration tokens.",
         api_surface="REST + GraphQL.",
         mcp="no", verdict="buildable",
         blocker="Auth flavors vary (OAuth 1.0a legacy); self-host effort.",
         evidence="https://developer.adobe.com/commerce/webapi/", confidence="medium"),
    dict(id=46, name="Squarespace", website="developers.squarespace.com", category="Ecommerce",
         one_liner="Website builder with commerce.",
         auth="OAuth2 + API key",
         self_serve="partial", serve_note="Commerce APIs available on paid plans; some APIs invite/partner.",
         api_surface="REST (Orders, Inventory, Products).",
         mcp="no", verdict="buildable",
         blocker="API access tied to plan; some endpoints partner-gated.",
         evidence="https://developers.squarespace.com/", confidence="medium"),
    dict(id=47, name="Ecwid", website="api-docs.ecwid.com", category="Ecommerce",
         one_liner="Embeddable store (Lightspeed).",
         auth="OAuth2 + token",
         self_serve="self-serve", serve_note="Register app; token per store.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://api-docs.ecwid.com/", confidence="high"),
    dict(id=48, name="Gumroad", website="gumroad.com/api", category="Ecommerce",
         one_liner="Sell digital products directly.",
         auth="OAuth2 + access token",
         self_serve="self-serve", serve_note="Access token from settings.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://app.gumroad.com/api", confidence="high"),
    dict(id=49, name="Amazon Selling Partner", website="developer-docs.amazon.com/sp-api", category="Ecommerce",
         one_liner="Amazon marketplace seller API.",
         auth="OAuth2 (Login with Amazon)",
         self_serve="gated", serve_note="Requires developer registration + approval; seller/vendor account.",
         api_surface="Broad SP-API.",
         mcp="no", verdict="buildable",
         blocker="Developer registration and approval process.",
         evidence="https://developer-docs.amazon.com/sp-api/", confidence="high"),
    dict(id=50, name="fanbasis", website="fanbasis.com", category="Ecommerce",
         one_liner="Payments/checkout and subscriptions for creators and coaches.",
         auth="API key (Bearer)",
         self_serve="self-serve", serve_note="Sign up (email+phone verify); sandbox + production environments; API key from dashboard.",
         api_surface="REST API (checkout sessions, subscriptions, customers, webhooks) + official Node/Python/PHP/Ruby SDKs.",
         mcp="no", verdict="easy",
         blocker="",
         evidence="https://apidocs.fan/", confidence="medium",
         verified=True, first_pass=dict(verdict="needs-human", auth="unknown", self_serve="unknown",
                                        api_surface="unknown / not clearly documented.", confidence="low")),

    # ------------------------------------------------------------------ #
    # 6. Data, SEO and Scraping
    # ------------------------------------------------------------------ #
    dict(id=51, name="DataForSEO", website="docs.dataforseo.com", category="Data, SEO & Scraping",
         one_liner="SEO and SERP data APIs.",
         auth="Basic (login + password)",
         self_serve="self-serve", serve_note="Sign up; credentials are your account login.",
         api_surface="Broad REST API (SERP, keywords, backlinks).",
         mcp="no", verdict="easy", blocker="",
         evidence="https://docs.dataforseo.com/v3/", confidence="high"),
    dict(id=52, name="SE Ranking", website="seranking.com/api", category="Data, SEO & Scraping",
         one_liner="SEO rank tracking / platform.",
         auth="API key (token)",
         self_serve="self-serve", serve_note="Token from account.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://seranking.com/api.html", confidence="medium"),
    dict(id=53, name="Ahrefs", website="ahrefs.com/api", category="Data, SEO & Scraping",
         one_liner="Backlink and SEO intelligence.",
         auth="API key (Bearer)",
         self_serve="partial", serve_note="API access requires a paid subscription / API plan.",
         api_surface="REST API.",
         mcp="no", verdict="buildable",
         blocker="API is behind a paid plan; no free tier for credentials.",
         evidence="https://docs.ahrefs.com/", confidence="medium"),
    dict(id=54, name="MrScraper", website="docs.mrscraper.com", category="Data, SEO & Scraping",
         one_liner="No-code / API web scraping.",
         auth="API key",
         self_serve="self-serve", serve_note="Key from dashboard.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://docs.mrscraper.com/", confidence="low"),
    dict(id=55, name="Apify", website="docs.apify.com", category="Data, SEO & Scraping",
         one_liner="Web scraping + automation actor platform.",
         auth="API token (Bearer)",
         self_serve="self-serve", serve_note="Free tier; token in console.",
         api_surface="REST API + Actor ecosystem.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://docs.apify.com/api/v2", confidence="high"),
    dict(id=56, name="Firecrawl", website="firecrawl.dev", category="Data, SEO & Scraping",
         one_liner="Turn websites into LLM-ready data.",
         auth="API key (Bearer)",
         self_serve="self-serve", serve_note="Free tier; key from dashboard.",
         api_surface="REST API (scrape/crawl/extract).",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://docs.firecrawl.dev/", confidence="high"),
    dict(id=57, name="Bright Data", website="brightdata.com", category="Data, SEO & Scraping",
         one_liner="Proxy network + web data platform.",
         auth="API token + Basic (proxy creds)",
         self_serve="self-serve", serve_note="Account; API token + zone credentials.",
         api_surface="REST API + proxy endpoints.",
         mcp="community", verdict="buildable",
         blocker="Product surface is broad and proxy-centric; onboarding is heavier.",
         evidence="https://docs.brightdata.com/", confidence="medium"),
    dict(id=58, name="Sherlock", website="github.com/sherlock-project/sherlock", category="Data, SEO & Scraping",
         one_liner="OSINT CLI that finds usernames across sites.",
         auth="none (open-source CLI, no API)",
         self_serve="self-serve", serve_note="Open-source; pip/clone and run — no credentials.",
         api_surface="CLI only; no hosted API.",
         mcp="no", verdict="buildable",
         blocker="Not an API — must be wrapped as an agent-callable skill/CLI, not an MCP-over-HTTP toolkit.",
         evidence="https://github.com/sherlock-project/sherlock", confidence="high"),
    dict(id=59, name="Waterfall.io", website="waterfall.io", category="Data, SEO & Scraping",
         one_liner="Contact/company intelligence and enrichment (customer-requested).",
         auth="unknown (likely API key)",
         self_serve="unknown", serve_note="No clearly documented public API surfaced on first pass.",
         api_surface="unknown.",
         mcp="unknown", verdict="needs-human",
         blocker="Public API docs not confirmed; agent flagged for human verification.",
         evidence="https://waterfall.io/", confidence="low"),
    dict(id=60, name="Clay", website="clay.com", category="Data, SEO & Scraping",
         one_liner="GTM data enrichment and automation.",
         auth="API key",
         self_serve="partial", serve_note="API/webhook access is on higher paid plans.",
         api_surface="REST API + webhooks (limited).",
         mcp="no", verdict="buildable",
         blocker="Programmatic access gated behind paid plan tiers.",
         evidence="https://www.clay.com/university/guide/api", confidence="medium"),

    # ------------------------------------------------------------------ #
    # 7. Developer, Infra and Data platforms
    # ------------------------------------------------------------------ #
    dict(id=61, name="GitHub", website="docs.github.com/rest", category="Developer, Infra & Data",
         one_liner="Code hosting and collaboration.",
         auth="OAuth2 + PAT + GitHub App",
         self_serve="self-serve", serve_note="Free account; PAT or app instantly.",
         api_surface="Very broad REST + GraphQL.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://docs.github.com/en/rest", confidence="high"),
    dict(id=62, name="Vercel", website="vercel.com/docs/rest-api", category="Developer, Infra & Data",
         one_liner="Frontend cloud / hosting.",
         auth="Bearer token + OAuth",
         self_serve="self-serve", serve_note="Free account; token in settings.",
         api_surface="REST API.",
         mcp="community", verdict="easy", blocker="",
         evidence="https://vercel.com/docs/rest-api", confidence="high"),
    dict(id=63, name="Netlify", website="docs.netlify.com/api", category="Developer, Infra & Data",
         one_liner="Web hosting and deploy platform.",
         auth="OAuth2 + PAT",
         self_serve="self-serve", serve_note="Free account; PAT in settings.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://docs.netlify.com/api/get-started/", confidence="high"),
    dict(id=64, name="Cloudflare", website="developers.cloudflare.com/api", category="Developer, Infra & Data",
         one_liner="CDN, DNS, security and edge platform.",
         auth="API token / API key (Bearer)",
         self_serve="self-serve", serve_note="Free account; scoped API token.",
         api_surface="Very broad REST API v4.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://developers.cloudflare.com/api/", confidence="high"),
    dict(id=65, name="Supabase", website="supabase.com/docs", category="Developer, Infra & Data",
         one_liner="Open-source Firebase alternative (Postgres).",
         auth="API key (anon/service) + Management API token",
         self_serve="self-serve", serve_note="Free project; keys in dashboard.",
         api_surface="Auto REST (PostgREST) + Management API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://supabase.com/docs/reference/api", confidence="high"),
    dict(id=66, name="Neo4j", website="neo4j.com/docs/api", category="Developer, Infra & Data",
         one_liner="Graph database.",
         auth="Basic auth / token",
         self_serve="self-serve", serve_note="Aura free tier or self-host; instance credentials.",
         api_surface="HTTP Query API + Bolt driver.",
         mcp="community", verdict="buildable",
         blocker="Query API + driver model; Cypher required.",
         evidence="https://neo4j.com/docs/query-api/", confidence="medium"),
    dict(id=67, name="Snowflake", website="docs.snowflake.com", category="Developer, Infra & Data",
         one_liner="Cloud data warehouse.",
         auth="OAuth2 + key-pair (JWT) + Basic",
         self_serve="self-serve", serve_note="30-day trial; account gives credentials.",
         api_surface="SQL REST API + drivers.",
         mcp="community", verdict="buildable",
         blocker="Auth (key-pair/OAuth) and account URL model add setup friction.",
         evidence="https://docs.snowflake.com/en/developer-guide/sql-api/index", confidence="high"),
    dict(id=68, name="MongoDB Atlas", website="mongodb.com/docs/atlas/api", category="Developer, Infra & Data",
         one_liner="Managed MongoDB cloud.",
         auth="API key (programmatic, digest/service account)",
         self_serve="self-serve", serve_note="Free tier cluster; programmatic API keys.",
         api_surface="Admin API + Data API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://www.mongodb.com/docs/atlas/api/", confidence="high"),
    dict(id=69, name="Datadog", website="docs.datadoghq.com/api", category="Developer, Infra & Data",
         one_liner="Monitoring and observability.",
         auth="API key + application key",
         self_serve="self-serve", serve_note="Trial; keys in org settings.",
         api_surface="Very broad REST API.",
         mcp="community", verdict="easy", blocker="",
         evidence="https://docs.datadoghq.com/api/latest/", confidence="high"),
    dict(id=70, name="Sentry", website="docs.sentry.io/api", category="Developer, Infra & Data",
         one_liner="Error tracking and performance monitoring.",
         auth="OAuth2 + auth token (Bearer)",
         self_serve="self-serve", serve_note="Free tier; auth token in settings.",
         api_surface="REST API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://docs.sentry.io/api/", confidence="high"),

    # ------------------------------------------------------------------ #
    # 8. Productivity and Project Management
    # ------------------------------------------------------------------ #
    dict(id=71, name="Notion", website="developers.notion.com", category="Productivity & PM",
         one_liner="Docs, wiki and databases workspace.",
         auth="OAuth2 + internal integration token",
         self_serve="self-serve", serve_note="Free account; create an integration for a token.",
         api_surface="REST API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://developers.notion.com/", confidence="high"),
    dict(id=72, name="Airtable", website="airtable.com/developers", category="Productivity & PM",
         one_liner="Spreadsheet-database hybrid.",
         auth="OAuth2 + personal access token",
         self_serve="self-serve", serve_note="Free account; PAT in settings.",
         api_surface="REST API + metadata API.",
         mcp="community", verdict="easy", blocker="",
         evidence="https://airtable.com/developers/web/api/introduction", confidence="high"),
    dict(id=73, name="Linear", website="developers.linear.app", category="Productivity & PM",
         one_liner="Issue tracking for software teams.",
         auth="OAuth2 + API key + GraphQL",
         self_serve="self-serve", serve_note="Free account; API key in settings.",
         api_surface="GraphQL-native API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://developers.linear.app/docs", confidence="high"),
    dict(id=74, name="Jira", website="developer.atlassian.com", category="Productivity & PM",
         one_liner="Project and issue tracking (Atlassian).",
         auth="OAuth2 (3LO) + API token (Basic)",
         self_serve="self-serve", serve_note="Free tier; API token from account.",
         api_surface="Broad REST API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://developer.atlassian.com/cloud/jira/platform/rest/v3/", confidence="high"),
    dict(id=75, name="Asana", website="developers.asana.com", category="Productivity & PM",
         one_liner="Work and project management.",
         auth="OAuth2 + PAT",
         self_serve="self-serve", serve_note="Free account; PAT in developer console.",
         api_surface="REST API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://developers.asana.com/docs", confidence="high"),
    dict(id=76, name="Monday.com", website="developer.monday.com", category="Productivity & PM",
         one_liner="Work OS / project management.",
         auth="OAuth2 + API token + GraphQL",
         self_serve="self-serve", serve_note="Trial; token in developer section.",
         api_surface="GraphQL-native API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://developer.monday.com/api-reference/docs", confidence="high"),
    dict(id=77, name="ClickUp", website="clickup.com/api", category="Productivity & PM",
         one_liner="All-in-one productivity/PM.",
         auth="OAuth2 + personal API token",
         self_serve="self-serve", serve_note="Free account; personal token in settings.",
         api_surface="REST API v2.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://developer.clickup.com/docs", confidence="high"),
    dict(id=78, name="Coda", website="coda.io/developers", category="Productivity & PM",
         one_liner="Docs that combine text, tables and apps.",
         auth="API token (Bearer)",
         self_serve="self-serve", serve_note="Free account; token in settings.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://coda.io/developers/apis/v1", confidence="high"),
    dict(id=79, name="Smartsheet", website="smartsheet.com/developers", category="Productivity & PM",
         one_liner="Spreadsheet-style work management.",
         auth="OAuth2 + access token (Bearer)",
         self_serve="self-serve", serve_note="Trial; access token in settings.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://smartsheet.redoc.ly/", confidence="high"),
    dict(id=80, name="Harvest", website="harvestapp.com", category="Productivity & PM",
         one_liner="Time tracking and invoicing.",
         auth="OAuth2 + PAT (account ID + token)",
         self_serve="self-serve", serve_note="Free trial; PAT from developer page.",
         api_surface="REST API v2.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://help.getharvest.com/api-v2/", confidence="high"),

    # ------------------------------------------------------------------ #
    # 9. Finance and Fintech
    # ------------------------------------------------------------------ #
    dict(id=81, name="Stripe", website="stripe.com/docs/api", category="Finance & Fintech",
         one_liner="Payments and financial infrastructure.",
         auth="API key (secret) + OAuth (Connect)",
         self_serve="self-serve", serve_note="Free account; test-mode keys instantly.",
         api_surface="Very broad REST API.",
         mcp="yes", verdict="easy", blocker="",
         evidence="https://stripe.com/docs/api", confidence="high"),
    dict(id=82, name="Plaid", website="plaid.com/docs", category="Finance & Fintech",
         one_liner="Bank account connectivity for fintech.",
         auth="API key (client_id + secret)",
         self_serve="partial", serve_note="Free sandbox is self-serve; production access requires approval.",
         api_surface="REST API.",
         mcp="no", verdict="buildable",
         blocker="Production requires a review/approval step (sandbox is open).",
         evidence="https://plaid.com/docs/api/", confidence="high"),
    dict(id=83, name="Binance", website="binance-docs.github.io", category="Finance & Fintech",
         one_liner="Crypto exchange.",
         auth="API key + HMAC-signed secret",
         self_serve="self-serve", serve_note="Account; create API key/secret (KYC applies).",
         api_surface="Broad REST + WebSocket.",
         mcp="community", verdict="buildable",
         blocker="HMAC request signing + regional availability constraints.",
         evidence="https://binance-docs.github.io/apidocs/", confidence="medium"),
    dict(id=84, name="Paygent Connect", website="paygent (NMI-powered)", category="Finance & Fintech",
         one_liner="Payment gateway connector (NMI-powered; customer-requested).",
         auth="gateway credentials / API key",
         self_serve="gated", serve_note="Requires a merchant/gateway account; NMI-based, sales/onboarding-led.",
         api_surface="NMI-style gateway API.",
         mcp="unknown", verdict="gated",
         blocker="Merchant/gateway account required; obscure branding — low confidence, flagged.",
         evidence="https://www.nmi.com/", confidence="low"),
    dict(id=85, name="iPayX", website="ipayx.ai/docs", category="Finance & Fintech",
         one_liner="Payments platform (customer-requested).",
         auth="unknown (likely API key)",
         self_serve="unknown", serve_note="Docs URL given but public API details not confirmed on first pass.",
         api_surface="unknown.",
         mcp="unknown", verdict="needs-human",
         blocker="Could not confirm public API; agent flagged for human verification.",
         evidence="https://ipayx.ai/docs", confidence="low"),
    dict(id=86, name="QuickBooks", website="developer.intuit.com", category="Finance & Fintech",
         one_liner="Small-business accounting (Intuit).",
         auth="OAuth2",
         self_serve="self-serve", serve_note="Free developer account + sandbox company.",
         api_surface="REST Accounting API.",
         mcp="no", verdict="buildable",
         blocker="OAuth2 + sandbox-to-production app review.",
         evidence="https://developer.intuit.com/app/developer/qbo/docs/get-started", confidence="high"),
    dict(id=87, name="Xero", website="developer.xero.com", category="Finance & Fintech",
         one_liner="Cloud accounting.",
         auth="OAuth2 (PKCE)",
         self_serve="self-serve", serve_note="Free developer account; create an app.",
         api_surface="REST API.",
         mcp="no", verdict="buildable",
         blocker="OAuth2 app + tenant selection.",
         evidence="https://developer.xero.com/documentation/", confidence="high"),
    dict(id=88, name="Brex", website="developer.brex.com", category="Finance & Fintech",
         one_liner="Corporate cards and spend management.",
         auth="OAuth2 + API token (Bearer)",
         self_serve="partial", serve_note="Requires a Brex customer account; then tokens are self-serve.",
         api_surface="REST API.",
         mcp="no", verdict="buildable",
         blocker="Must be a Brex customer to get credentials.",
         evidence="https://developer.brex.com/", confidence="medium"),
    dict(id=89, name="Ramp", website="docs.ramp.com", category="Finance & Fintech",
         one_liner="Corporate cards and finance automation.",
         auth="OAuth2 (client credentials)",
         self_serve="partial", serve_note="Requires a Ramp customer account to provision API access.",
         api_surface="REST API.",
         mcp="no", verdict="buildable",
         blocker="Customer account required to obtain OAuth client.",
         evidence="https://docs.ramp.com/", confidence="medium"),
    dict(id=90, name="PitchBook", website="pitchbook.com", category="Finance & Fintech",
         one_liner="Private-market research and data.",
         auth="API key / token",
         self_serve="gated", serve_note="Enterprise data license; contact-sales, no self-serve.",
         api_surface="REST research API.",
         mcp="no", verdict="gated",
         blocker="Enterprise data licensing / partnership required.",
         evidence="https://pitchbook.com/", confidence="medium"),

    # ------------------------------------------------------------------ #
    # 10. AI, Research and Media-native
    # ------------------------------------------------------------------ #
    dict(id=91, name="NotebookLM", website="cloud.google.com/gemini", category="AI, Research & Media-native",
         one_liner="Google's AI research/notebook tool.",
         auth="OAuth2 (Google Cloud / Gemini Enterprise)",
         self_serve="gated", serve_note="No standalone NotebookLM API; access is via Gemini Enterprise, enterprise-gated.",
         api_surface="Via Gemini Enterprise API only.",
         mcp="no", verdict="gated",
         blocker="No public standalone API for NotebookLM itself; enterprise Gemini gate.",
         evidence="https://cloud.google.com/gemini/docs", confidence="medium"),
    dict(id=92, name="Otter AI", website="help.otter.ai", category="AI, Research & Media-native",
         one_liner="Meeting transcription and notes.",
         auth="OAuth2 (Claude/ChatGPT connector) + bearer token (Enterprise API, beta)",
         self_serve="partial", serve_note="Official MCP connector is self-serve via OAuth; the raw REST API is beta and Enterprise-plan only (account-manager gated).",
         api_surface="Official MCP server (search/list/fetch transcripts); public REST API is beta, Enterprise-only.",
         mcp="yes", verdict="buildable",
         blocker="Raw API is Enterprise-gated; broad access goes through the MCP server.",
         evidence="https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server", confidence="medium",
         verified=True, first_pass=dict(auth="OAuth2 (via MCP server) / limited", confidence="low")),
    dict(id=93, name="Fathom", website="fathom.video", category="AI, Research & Media-native",
         one_liner="AI meeting notetaker.",
         auth="API key (emerging)",
         self_serve="partial", serve_note="API access is limited/emerging; not a broad public API yet.",
         api_surface="Limited/emerging API.",
         mcp="unknown", verdict="buildable",
         blocker="API surface is thin/early; coverage uncertain.",
         evidence="https://fathom.video/", confidence="low"),
    dict(id=94, name="Consensus", website="consensus.app", category="AI, Research & Media-native",
         one_liner="AI-powered scientific research search.",
         auth="OAuth2 (requested per brief)",
         self_serve="gated", serve_note="Brief notes OAuth 'requested'; no self-serve public API confirmed yet.",
         api_surface="Emerging; not publicly documented.",
         mcp="unknown", verdict="gated",
         blocker="No public API yet; OAuth requested — needs vendor conversation.",
         evidence="https://consensus.app/", confidence="low"),
    dict(id=95, name="Reducto", website="reducto.ai", category="AI, Research & Media-native",
         one_liner="Document parsing / ingestion for AI (parse, split, extract, edit).",
         auth="API key (Bearer, REDUCTO_API_KEY)",
         self_serve="self-serve", serve_note="Sign up free at Studio and create an API key; enterprise tier is sales-led.",
         api_surface="REST API (parse/split/extract/edit) + Python/Node/Go SDKs + CLI + MCP server.",
         mcp="yes", verdict="easy",
         blocker="",
         evidence="https://docs.reducto.ai/quickstart", confidence="high",
         verified=True, first_pass=dict(mcp="no", api_surface="REST API (parse/extract).", confidence="medium")),
    dict(id=96, name="Devin", website="docs.devin.ai", category="AI, Research & Media-native",
         one_liner="AI software engineer agent (Cognition).",
         auth="API key + MCP",
         self_serve="partial", serve_note="Paid product; API key + MCP once subscribed.",
         api_surface="REST API + MCP.",
         mcp="yes", verdict="buildable",
         blocker="Paid subscription required for credentials.",
         evidence="https://docs.devin.ai/", confidence="medium"),
    dict(id=97, name="higgsfield", website="higgsfield.ai/cli", category="AI, Research & Media-native",
         one_liner="AI content/creative suite (CLI hint).",
         auth="API key / CLI auth",
         self_serve="partial", serve_note="CLI-based; account required. API breadth uncertain.",
         api_surface="CLI + likely API; uncertain.",
         mcp="unknown", verdict="buildable",
         blocker="CLI-first; programmatic surface unclear — medium/low confidence.",
         evidence="https://higgsfield.ai/", confidence="low"),
    dict(id=98, name="Mermaid CLI", website="github.com/mermaid-js/mermaid-cli", category="AI, Research & Media-native",
         one_liner="Render Mermaid diagrams from the command line.",
         auth="none (open-source npm CLI)",
         self_serve="self-serve", serve_note="Open source; install via npm — no credentials.",
         api_surface="CLI only; no hosted API.",
         mcp="no", verdict="buildable",
         blocker="Not an API — wrap as an agent-callable skill/CLI, not an HTTP toolkit.",
         evidence="https://github.com/mermaid-js/mermaid-cli", confidence="high"),
    dict(id=99, name="YouTube Transcript", website="transcriptapi.com", category="AI, Research & Media-native",
         one_liner="Fetch YouTube video transcripts via API.",
         auth="API key",
         self_serve="self-serve", serve_note="Sign up; API key from dashboard.",
         api_surface="REST API.",
         mcp="no", verdict="easy", blocker="",
         evidence="https://www.transcriptapi.com/", confidence="medium"),
    dict(id=100, name="Grain", website="grain.com", category="AI, Research & Media-native",
         one_liner="Meeting recording and notes.",
         auth="OAuth2 + API key",
         self_serve="partial", serve_note="Account required; OAuth/API for integrations.",
         api_surface="REST API.",
         mcp="no", verdict="buildable",
         blocker="Integration/API tied to account plan.",
         evidence="https://grain.com/", confidence="low"),
]

if __name__ == "__main__":
    import json, sys
    print(f"{len(APPS)} apps loaded", file=sys.stderr)
    print(json.dumps(APPS, indent=2))
